### ISSUE TITLE
State rendering serverside ?

### ISSUE THREAD

**Issue by andyfen** [kuuup/mobx-ssr-example#1]
Is it possible to make the state render and update on the server i.e if javascript was disabled on the client ?

**Comment by kuuup-at-work** [comment]
Sure. You can update your state on the server. This example doesn't cover a permanent state because it creates a new AppState on each request. But you can save your state somewhere else so you can update it over time.

For example you could move this line

``` javascript
const appstate = new AppState();
```

just below your imports.

Then you can replace this code:

``` javascript
appstate.addItem('foo');
appstate.addItem('bar');
```

with something like

``` javascript
if(req.query.addItem) appstate.addItem(req.query.addItem);
```

Then update your state by adding a query parameter

```
yourserver:3000/?addItem=baz
```

These changes result in a warning (see https://github.com/mobxjs/mobx/issues/512) but it works and gives you an idea of how this could be implemented.
It doesn't matter how your client creates a link with the right parameter so theoretically no javascript is needed on your browser.

**Comment by andyfen** [comment]
thanks. i've been looking at a few router examples that use 

```
`<script>
    window.__PRELOADED_STATE__ = ${JSON.stringify(state)}
</script>`
```

then inject it back in with

```
const state = JSON.parse(window.__PRELOADED_STATE__ || '{}');
let store = window.store = new Store(state);
```

**Comment by kuuup-at-work** [comment]
I don't understand what you're trying to do, because you asked for a way to update state on the server and your second comment is about client code. 

See https://github.com/kuuup/mobx-ssr-example/blob/master/src/client/index.js#L12
It's exactly what you saw in other examples. 

But you can transfer your state in both directions, then init your stores with this state and then render it with react. From backend to client you transfer the serialized state with rendered stuff so you can display it immediately. From client to backend you only need to transfer the state (set by a POST request or by url).

Maybe you have some example code I could look at to give you a better answer.
